# Generated by Django 6.0.3 on 2026-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarchProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_series', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('lot_number', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('customer', models.CharField(default='Stock', max_length=200)),
                ('target_units', models.PositiveIntegerField(default=1)),
                ('total_planned', models.PositiveIntegerField()),
                ('is_produced', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['production_date', 'line_series', 'lot_number'],
            },
        ),
    ]
