# Generated by Django 6.0.3 on 2026-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarchProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('N', 'N-SERIES'), ('F', 'F-SERIES')], max_length=1)),
                ('model_name', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=20)),
                ('ckd_arrival_iea', models.CharField(default='ISUZU EA', max_length=50)),
                ('ckd_thailand', models.CharField(blank=True, max_length=50, null=True)),
                ('prd_customer', models.CharField(help_text='e.g., GSU Green, Tanesco green', max_length=200)),
                ('production_date', models.DateField()),
                ('daily_quantity', models.PositiveIntegerField(default=1)),
                ('lot_total_units', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['production_date', 'line', 'lot_number'],
            },
        ),
        migrations.DeleteModel(
            name='MarchProduction',
        ),
    ]
