# Generated by Django 6.0.3 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_marchproductiontask_delete_marchproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchproductiontask',
            name='prd_customer',
            field=models.CharField(blank=True, help_text='e.g., GSU Green, Tanesco green', max_length=200, null=True),
        ),
    ]
