# Generated by Django 6.0.3 on 2026-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_marchproductiontask_prd_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarchProductionTask',
            new_name='ProductionTask',
        ),
    ]
